web:
  build: ./
  ports:
    - "81:80"
  volumes:
    - .:/var/www/html/
  links:
    - mysql
  hostname: mage7.local
  environment:
      XDEBUG_CONFIG: remote_host={$local_ip}
mysql:
  image: mysql:5.6
  ports:
     - 3307:3306
  volumes:
     - ./docker/dump:/docker-entrypoint-initdb.d
  environment:
     - MYSQL_ROOT_PASSWORD=123456
     - MYSQL_DATABASE=magenew